# Generated by Django 3.0.5 on 2020-04-29 18:40

from django.db import migrations, models
import django.db.models.deletion
import lab1app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=261, verbose_name='Имя файла')),
                ('file_content', models.FileField(upload_to='documents/', validators=[lab1app.validators.validate_file_extension], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='FileStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(verbose_name='Количество загрузок')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1app.File')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
